// AUTO-GENERATED by scripts/node/build_legal_content.mjs — do not edit by hand.
// 出典: app-flux (contact translations.ts / privacy-policy.astro / item_terms_of_use.astro)。
// 更新: app-flux 側を直して `node scripts/node/build_legal_content.mjs` で再生成。
export type LegalBlock = { p?: string; ul?: string[]; h3?: string; link?: { href: string; label: string } }
export type LegalSection = { title: string; blocks: LegalBlock[] }
export interface LegalLang {
  contact: { title: string; subjectLabel: string; subjectPlaceholder: string; subjects: string[]; nameLabel: string; emailLabel: string; messageLabel: string; submitButton: string; confirm: string }
  privacy: { title: string; intro: string; sections: LegalSection[] }
  terms: { title: string; intro: string; articles: { title: string; body: string }[] }
}

export const legalContent: Record<'en' | 'ja' | 'zh', LegalLang> = {
  "en": {
    "contact": {
      "title": "Contact",
      "subjectLabel": "Subject",
      "subjectPlaceholder": "Please select a subject",
      "subjects": [
        "About mobile app bugs or Facebook reports",
        "Inquiry about app development",
        "Other inquiry"
      ],
      "nameLabel": "Name",
      "emailLabel": "Email address",
      "messageLabel": "Message",
      "submitButton": "Send",
      "confirm": "Are you sure you want to send?"
    },
    "privacy": {
      "title": "Privacy Policy for Google Play Android Apps",
      "intro": "This privacy policy applies to the Android apps (hereinafter referred to as \"the App\") provided by App Flux Portal on Google Play.",
      "sections": [
        {
          "title": "1. Business Information",
          "blocks": [
            {
              "ul": [
                "Operator: BRANDO,K.K.",
                "Contact: Please use the contact form on this site"
              ]
            }
          ]
        },
        {
          "title": "2. User Data Collection",
          "blocks": [
            {
              "p": "The App does not collect any user data as follows:"
            },
            {
              "ul": [
                "Personal information such as names, email addresses, and phone numbers",
                "Identification information such as device IDs, advertising IDs, and location data",
                "Behavioral data such as usage history and access logs"
              ]
            },
            {
              "p": "The following declaration is also made in the \"Data Safety\" section of Google Play:"
            },
            {
              "ul": [
                "No data collection declared → The developer declares that the App does not collect user data.",
                "No data shared with third parties → The developer declares that the App does not share user data with other companies or organizations."
              ]
            }
          ]
        },
        {
          "title": "3. Data Use and Third-Party Provision",
          "blocks": [
            {
              "p": "As stated above, since the App does not collect user data, the following actions are never performed:"
            },
            {
              "ul": [
                "Analysis or secondary use of collected personal information or usage data",
                "Use of data for advertising or marketing purposes",
                "Provision or sharing with third parties (advertising networks, analytics providers, etc.)"
              ]
            }
          ]
        },
        {
          "title": "4. Permissions and External Services Used",
          "blocks": [
            {
              "p": "The App uses only the minimum functionality necessary to provide its features, and does not currently use the following device permissions:"
            },
            {
              "ul": [
                "Location information (GPS, etc.)",
                "Contacts",
                "Camera",
                "Microphone",
                "Call history",
                "SMS and other communication-related permissions"
              ]
            },
            {
              "p": "Additionally, the following external services are not currently used:"
            },
            {
              "ul": [
                "Ad serving services (e.g., AdMob)",
                "Analytics services (e.g., Google Analytics for Firebase)"
              ]
            },
            {
              "p": "If these services or permissions are used in the future, this privacy policy will be updated in advance, and the \"Data Safety\" declaration on Google Play will be changed accordingly."
            }
          ]
        },
        {
          "title": "5. Children's Privacy and Play Family Policy",
          "blocks": [
            {
              "p": "The App is designed to be safely used by general users, including children. The developer strives to comply with Google Play's Play Family Policy."
            },
            {
              "ul": [
                "The App is designed not to collect children's personal information.",
                "Care is taken to avoid inappropriate content or excessive advertising."
              ]
            }
          ]
        },
        {
          "title": "6. Information That May Be Collected by Websites",
          "blocks": [
            {
              "p": "This privacy policy primarily concerns \"the App,\" but if the App displays websites such as App Flux Portal in an external browser, those sites may collect cookies, access logs, etc. In such cases, the data will be handled according to the separate privacy policy posted on the respective site."
            }
          ]
        },
        {
          "title": "7. Compliance with Google Play Policies",
          "blocks": [
            {
              "p": "The developer of the App respects the various policies set by Google and strives to comply with the following:"
            },
            {
              "h3": "7-1. Permissions and APIs for Access to User Data and Sensitive Information"
            },
            {
              "ul": [
                "The App does not currently request permissions or APIs that access sensitive user data (location information, contacts, media files, call history, etc.).",
                "If it becomes necessary to use these permissions or APIs in the future, the purpose will be clearly stated, limited to the minimum necessary scope, explained clearly in the App and store listing information, and implemented in accordance with Google Play policies."
              ]
            },
            {
              "h3": "7-2. Misrepresentation (Prohibition of Deceptive Apps)"
            },
            {
              "ul": [
                "The App is designed so that the store listing information and in-app display content match the actual behavior.",
                "The App does not contain malware-like functions, undisclosed hidden features, or unauthorized code for other purposes.",
                "Care is taken to avoid using misleading descriptions, screenshots, icons, etc. that could confuse users."
              ]
            },
            {
              "h3": "7-3. Prohibition of Fraudulent Activities on Devices and Networks"
            },
            {
              "ul": [
                "The App does not perform any actions prohibited by Google Play policies, such as unauthorized access to devices or networks, spam sending, ranking manipulation, or cryptocurrency mining.",
                "No processing is performed that is intended to cause unintended load or damage to users' devices or networks."
              ]
            },
            {
              "h3": "7-4. Google Play Target API Level Policy"
            },
            {
              "ul": [
                "The App is built to meet the target API level requirements required by Google Play at the time of publication.",
                "We strive to update the target API level and modify the App as appropriate in response to changes in Google requirements."
              ]
            },
            {
              "h3": "7-5. Prohibition of Deceptive Behavior"
            },
            {
              "ul": [
                "The App is designed to avoid UI designs that deceive users or displays that induce mistaps (so-called confusing button placement, etc.).",
                "The App is not designed to perform communications or processing in the background for purposes that users are not aware of.",
                "If advertising is introduced in the future, we will prioritize Google Play policies and user-friendliness."
              ]
            }
          ]
        },
        {
          "title": "8. Paid Items (In-App Purchases) Terms",
          "blocks": [
            {
              "p": "These terms define the conditions for using paid items (in-app purchases). Please review the full terms via the link below."
            },
            {
              "link": {
                "href": "/en/item_terms_of_use/",
                "label": "Open Paid Items Terms in a window"
              }
            }
          ]
        },
        {
          "title": "9. Security Measures",
          "blocks": [
            {
              "ul": [
                "Although the App is designed not to collect user data, if we add features that handle data in the future, we will strive to implement appropriate technical and organizational security measures to prevent unauthorized access, tampering, and leakage.",
                "We will also regularly review the Play Family Policy and related policies, and revise the App and operations as necessary."
              ]
            }
          ]
        },
        {
          "title": "10. Changes to This Privacy Policy",
          "blocks": [
            {
              "p": "The content of this privacy policy may be changed as necessary."
            },
            {
              "ul": [
                "If there are significant changes, we will announce them in the App or on App Flux Portal.",
                "The revised privacy policy will take effect from the time it is posted on this site."
              ]
            }
          ]
        }
      ]
    },
    "terms": {
      "title": "Paid Items (In-App Purchases) Terms",
      "intro": "These terms (the \"Terms\") define the conditions for using paid items (the \"Items\") provided within the App. By using the App, the user is deemed to have agreed to these Terms.",
      "articles": [
        {
          "title": "Article 1 (About Paid Items)",
          "body": "Paid items offered within the App are one-time purchase digital content. By purchasing an item, the user obtains the right to use the item within the App. Paid items do not guarantee permanent operation or future availability."
        },
        {
          "title": "Article 2 (Usage Environment)",
          "body": "Items are provided based on the App and operating environment at the time of purchase. Items may stop functioning properly due to OS updates, device changes, or changes by manufacturers or carriers. The developer assumes no responsibility for these issues."
        },
        {
          "title": "Article 3 (Updates and Continued Provision)",
          "body": "The developer is not obligated to provide continuous updates or improvements for the App or Items. The developer may change, suspend, or terminate the provision of the App or Items without notice."
        },
        {
          "title": "Article 4 (Service Termination)",
          "body": "The developer may terminate the provision of the App or Items for operational or technical reasons. After termination, items may no longer be usable."
        },
        {
          "title": "Article 5 (Refunds)",
          "body": "Due to the nature of digital content, refunds are generally not provided after purchase. However, the refund policies of platforms such as the Google Play Store take precedence."
        },
        {
          "title": "Article 6 (Disclaimer)",
          "body": "The developer is not responsible for any damages incurred by users from using the App or Items. The App and Items are provided on an \"as-is\" basis."
        },
        {
          "title": "Article 7 (Changes to the Terms)",
          "body": "The developer may change these Terms as necessary. The revised Terms take effect when posted in the App or on related websites."
        },
        {
          "title": "Article 8 (Governing Law)",
          "body": "These Terms are governed by and construed in accordance with the laws of Japan."
        }
      ]
    }
  },
  "ja": {
    "contact": {
      "title": "Contact",
      "subjectLabel": "件名",
      "subjectPlaceholder": "件名を選択してください",
      "subjects": [
        "モバイルアプリのバグやFacebook報告について",
        "アプリ開発に関するお問い合わせ",
        "その他のお問い合わせ"
      ],
      "nameLabel": "お名前",
      "emailLabel": "メールアドレス",
      "messageLabel": "メッセージ",
      "submitButton": "送信",
      "confirm": "送信してもよろしいですか？"
    },
    "privacy": {
      "title": "Google Play Android アプリ プライバシーポリシー",
      "intro": "App Flux Portal が提供する、Google Play の Android アプリ（以下「本アプリ」）のプライバシーポリシーを、以下のとおり定めます。",
      "sections": [
        {
          "title": "1. 事業者情報",
          "blocks": [
            {
              "ul": [
                "運営者：株式会社ブランドー",
                "お問い合わせ先：本サイトのお問い合わせフォームをご利用ください"
              ]
            }
          ]
        },
        {
          "title": "2. 収集するユーザーデータについて",
          "blocks": [
            {
              "p": "本アプリは、次のとおり ユーザーデータを収集しません。"
            },
            {
              "ul": [
                "氏名、メールアドレス、電話番号などの個人情報",
                "端末 ID、広告 ID、位置情報などの識別情報",
                "利用履歴、アクセスログなどの行動データ"
              ]
            },
            {
              "p": "Google Play の「データ安全性」セクションにおいても、以下のとおり申告しています。"
            },
            {
              "ul": [
                "データ収集は申告されていません → 本アプリはユーザーデータを収集しないことをデベロッパーが申告しています。",
                "第三者と共有されるデータはありません → 本アプリは他の企業や組織とユーザーデータを共有しないことをデベロッパーが申告しています。"
              ]
            }
          ]
        },
        {
          "title": "3. データの利用・第三者提供について",
          "blocks": [
            {
              "p": "前項のとおり、本アプリではユーザーデータを収集していないため、次の行為は一切行いません。"
            },
            {
              "ul": [
                "取得した個人情報・利用データの分析・二次利用",
                "広告やマーケティング目的でのデータ利用",
                "第三者（広告ネットワーク、分析事業者など）への提供・共有"
              ]
            }
          ]
        },
        {
          "title": "4. 利用する権限・外部サービスについて",
          "blocks": [
            {
              "p": "本アプリは、提供する機能に必要な最小限の機能のみを利用し、以下のような端末権限は 現時点では使用しません。"
            },
            {
              "ul": [
                "位置情報（GPS 等）",
                "連絡先",
                "カメラ",
                "マイク",
                "通話履歴",
                "SMS など通信関連の権限"
              ]
            },
            {
              "p": "また、次のような外部サービスは 現時点では利用していません。"
            },
            {
              "ul": [
                "広告配信サービス（例：AdMob 等）",
                "アクセス解析サービス（例：Google Analytics for Firebase 等）"
              ]
            },
            {
              "p": "将来的にこれらのサービスや権限を利用する場合は、事前に本プライバシーポリシーを更新し、Google Play 上の「データ安全性」の申告内容もあわせて変更します。"
            }
          ]
        },
        {
          "title": "5. 子どものプライバシーと Play ファミリー ポリシー",
          "blocks": [
            {
              "p": "本アプリは、子どもを含む一般ユーザーが安心して利用できるように設計されています。デベロッパーは、Google Play の Play ファミリー ポリシーの遵守に努めています。"
            },
            {
              "ul": [
                "子どもの個人情報を収集しない設計としています。",
                "不適切なコンテンツや過度な広告表示を行わないよう配慮します。"
              ]
            }
          ]
        },
        {
          "title": "6. サイト側で取得される可能性のある情報について",
          "blocks": [
            {
              "p": "本プライバシーポリシーは主に「本アプリ」に関するものですが、本アプリから外部ブラウザで App Flux Portal 等のウェブサイトを表示する場合、そのサイト側で Cookie やアクセスログ等を取得することがあります。その場合は、当該サイトに掲載される別途のプライバシーポリシーに従って取り扱われます。"
            }
          ]
        },
        {
          "title": "7. Google Play ポリシーの遵守について",
          "blocks": [
            {
              "p": "本アプリのデベロッパーは、Google が定める各種ポリシーを尊重し、以下の内容を遵守するよう努めています。"
            },
            {
              "h3": "7-1. ユーザーデータおよび機密情報へのアクセスに関する権限と API"
            },
            {
              "ul": [
                "本アプリは、機密性の高いユーザーデータ（位置情報、連絡先、メディアファイル、通話履歴など）にアクセスする権限や API を 現時点では要求していません。",
                "将来、これらの権限・API を利用する必要が生じた場合には、利用目的を明確にし、必要最小限の範囲に限定し、アプリ内およびストア掲載情報でわかりやすく説明したうえで、Google Play のポリシーに従って実装します。"
              ]
            },
            {
              "h3": "7-2. 不実表示（虚偽のあるアプリの禁止）"
            },
            {
              "ul": [
                "本アプリは、ストア掲載情報やアプリ内の表示内容と実際の動作が一致するように設計しています。",
                "マルウェア的な機能、ユーザーに告知していない隠し機能、他用途のための不正なコード等は含んでいません。",
                "ユーザーに誤解を与えるような説明、スクリーンショット、アイコン等の使用を行わないよう配慮します。"
              ]
            },
            {
              "h3": "7-3. デバイスやネットワークでの不正行為の禁止"
            },
            {
              "ul": [
                "本アプリは、デバイスやネットワークに対する不正アクセス、スパム送信、ランキング操作、暗号資産マイニングなど、Google Play ポリシーで禁止されている行為を一切行いません。",
                "利用者のデバイスやネットワークに対して、意図しない負荷や損害を与えることを目的とした処理は行いません。"
              ]
            },
            {
              "h3": "7-4. Google Play の対象 API レベルに関するポリシー"
            },
            {
              "ul": [
                "本アプリは、公開時点で Google Play が要求する 対象 API レベルの要件を満たすようにビルドしています。",
                "Google の要件変更に応じて、適宜ターゲット API レベルの更新やアプリの改修を行うよう努めます。"
              ]
            },
            {
              "h3": "7-5. 虚偽の振る舞いの禁止"
            },
            {
              "ul": [
                "本アプリは、ユーザーを欺くような UI 設計や、誤タップを誘発する表示（いわゆる紛らわしいボタン配置など）を行わないよう配慮します。",
                "バックグラウンドでユーザーの認識していない目的の通信や処理を行うことを意図して設計していません。",
                "今後、広告などを導入する場合にも、Google Play のポリシーとユーザーにとっての分かりやすさを重視します。"
              ]
            }
          ]
        },
        {
          "title": "8. 有料アイテム（アプリ内課金）利用規約",
          "blocks": [
            {
              "p": "有料アイテム（アプリ内課金）の利用条件を定めています。詳細は以下のリンクからご確認ください。"
            },
            {
              "link": {
                "href": "/ja/item_terms_of_use/",
                "label": "有料アイテム利用規約を表示"
              }
            }
          ]
        },
        {
          "title": "9. セキュリティ対策",
          "blocks": [
            {
              "ul": [
                "本アプリはユーザーデータを収集しない設計としていますが、将来的にデータを扱う機能を追加する場合には、不正アクセス、改ざん、漏えい等を防ぐための適切な技術的・組織的安全管理措置を講じるよう努めます。",
                "また、Play ファミリー ポリシーおよび関連ポリシーを定期的に確認し、必要に応じてアプリや運用を見直します。"
              ]
            }
          ]
        },
        {
          "title": "10. プライバシーポリシーの変更について",
          "blocks": [
            {
              "p": "本プライバシーポリシーの内容は、必要に応じて変更される場合があります。"
            },
            {
              "ul": [
                "重要な変更がある場合は、本アプリまたは App Flux Portal 上で告知します。",
                "変更後のプライバシーポリシーは、当サイトに掲載された時点から効力を生じるものとします。"
              ]
            }
          ]
        }
      ]
    },
    "terms": {
      "title": "有料アイテム（アプリ内課金）利用規約",
      "intro": "本利用規約（以下「本規約」）は、本アプリおよび本アプリ内で提供される有料アイテム（以下「本アイテム」）の利用条件を定めるものです。ユーザーは、本アプリを利用することにより、本規約に同意したものとみなされます。",
      "articles": [
        {
          "title": "第1条（有料アイテムについて）",
          "body": "本アプリ内で提供される有料アイテムは、買い切り型のデジタルコンテンツです。本アイテムの購入により、ユーザーは本アプリ内で当該アイテムを利用する権利を取得します。本アイテムは、永続的な動作や将来にわたる利用を保証するものではありません。"
        },
        {
          "title": "第2条（利用環境について）",
          "body": "本アイテムは、購入時点での本アプリおよび動作環境を前提として提供されます。OSのアップデート、端末の変更、メーカーや通信事業者の仕様変更等により、本アイテムが正常に動作しなくなる場合があります。これらについて、開発者は一切の責任を負いません。"
        },
        {
          "title": "第3条（更新および提供の継続）",
          "body": "開発者は、本アプリおよび本アイテムについて、継続的なアップデートや機能改善を行う義務を負いません。開発者は、予告なく本アプリまたは本アイテムの提供を変更、停止、または終了することがあります。"
        },
        {
          "title": "第4条（サービス終了）",
          "body": "開発者は、運営上または技術上の理由により、本アプリおよび本アイテムの提供を終了することがあります。サービス終了後は、本アイテムを利用できなくなる場合があります。"
        },
        {
          "title": "第5条（返金について）",
          "body": "デジタルコンテンツの性質上、本アイテムの購入後の返金は原則として行われません。ただし、返金については、Google Play ストア等の各プラットフォームが定める返金ポリシーが優先されます。"
        },
        {
          "title": "第6条（免責事項）",
          "body": "開発者は、本アプリおよび本アイテムの利用によりユーザーに生じた損害について、一切の責任を負いません。本アプリおよび本アイテムは、現状有姿で提供されます。"
        },
        {
          "title": "第7条（規約の変更）",
          "body": "開発者は、必要に応じて本規約を変更することがあります。変更後の規約は、本アプリ内または関連サイトに掲載した時点で効力を生じます。"
        },
        {
          "title": "第8条（準拠法）",
          "body": "本規約は、日本法に準拠し解釈されます。"
        }
      ]
    }
  },
  "zh": {
    "contact": {
      "title": "Contact",
      "subjectLabel": "主题",
      "subjectPlaceholder": "请选择主题",
      "subjects": [
        "关于移动应用的漏洞或 Facebook 报告",
        "关于应用开发的咨询",
        "其他咨询"
      ],
      "nameLabel": "姓名",
      "emailLabel": "电子邮箱",
      "messageLabel": "留言",
      "submitButton": "发送",
      "confirm": "确定要发送吗？"
    },
    "privacy": {
      "title": "Google Play Android 应用隐私政策",
      "intro": "App Flux Portal 在 Google Play 上提供的 Android 应用（以下简称\"本应用\"）的隐私政策如下。",
      "sections": [
        {
          "title": "1. 运营者信息",
          "blocks": [
            {
              "ul": [
                "运营者：BRANDO,K.K.",
                "联系方式：请使用本网站的联系表单"
              ]
            }
          ]
        },
        {
          "title": "2. 关于用户数据收集",
          "blocks": [
            {
              "p": "本应用不收集以下任何用户数据："
            },
            {
              "ul": [
                "姓名、电子邮件地址、电话号码等个人信息",
                "设备 ID、广告 ID、位置信息等识别信息",
                "使用历史记录、访问日志等行为数据"
              ]
            },
            {
              "p": "在 Google Play 的\"数据安全性\"部分也做出了以下声明："
            },
            {
              "ul": [
                "未声明数据收集 → 开发者声明本应用不收集用户数据。",
                "不与第三方共享数据 → 开发者声明本应用不与其他公司或组织共享用户数据。"
              ]
            }
          ]
        },
        {
          "title": "3. 关于数据使用和第三方提供",
          "blocks": [
            {
              "p": "如上所述，由于本应用不收集用户数据，因此绝不会执行以下行为："
            },
            {
              "ul": [
                "分析或二次使用收集的个人信息或使用数据",
                "将数据用于广告或营销目的",
                "向第三方（广告网络、分析提供商等）提供或共享"
              ]
            }
          ]
        },
        {
          "title": "4. 关于使用的权限和外部服务",
          "blocks": [
            {
              "p": "本应用仅使用提供其功能所需的最小功能，目前不使用以下设备权限："
            },
            {
              "ul": [
                "位置信息（GPS 等）",
                "联系人",
                "相机",
                "麦克风",
                "通话记录",
                "SMS 等通信相关权限"
              ]
            },
            {
              "p": "此外，目前不使用以下外部服务："
            },
            {
              "ul": [
                "广告投放服务（例如：AdMob 等）",
                "访问分析服务（例如：Google Analytics for Firebase 等）"
              ]
            },
            {
              "p": "如果将来使用这些服务或权限，我们将事先更新本隐私政策，并相应更改 Google Play 上的\"数据安全性\"声明内容。"
            }
          ]
        },
        {
          "title": "5. 儿童隐私和 Play 家庭政策",
          "blocks": [
            {
              "p": "本应用旨在让包括儿童在内的普通用户能够安全使用。开发者致力于遵守 Google Play 的 Play 家庭政策。"
            },
            {
              "ul": [
                "本应用设计为不收集儿童的个人信息。",
                "注意避免不适当的内容或过度的广告展示。"
              ]
            }
          ]
        },
        {
          "title": "6. 关于网站可能收集的信息",
          "blocks": [
            {
              "p": "本隐私政策主要涉及\"本应用\"，但如果本应用在外部浏览器中显示 App Flux Portal 等网站，该网站可能会收集 Cookie、访问日志等。在这种情况下，数据将根据该网站上发布的单独隐私政策进行处理。"
            }
          ]
        },
        {
          "title": "7. 关于遵守 Google Play 政策",
          "blocks": [
            {
              "p": "本应用的开发者尊重 Google 制定的各项政策，并努力遵守以下内容："
            },
            {
              "h3": "7-1. 访问用户数据和敏感信息的权限和 API"
            },
            {
              "ul": [
                "本应用目前不请求访问敏感用户数据（位置信息、联系人、媒体文件、通话记录等）的权限或 API。",
                "如果将来需要使用这些权限或 API，我们将明确说明使用目的，限制在必要的最小范围内，在应用内和商店列表信息中清楚解释，并按照 Google Play 政策实施。"
              ]
            },
            {
              "h3": "7-2. 虚假陈述（禁止欺骗性应用）"
            },
            {
              "ul": [
                "本应用的设计使商店列表信息和应用内显示内容与实际行为一致。",
                "不包含恶意软件功能、未披露的隐藏功能或用于其他目的的未授权代码。",
                "注意避免使用可能误导用户的说明、屏幕截图、图标等。"
              ]
            },
            {
              "h3": "7-3. 禁止在设备和网络上的欺诈行为"
            },
            {
              "ul": [
                "本应用不执行 Google Play 政策禁止的任何行为，例如对设备或网络的未授权访问、垃圾邮件发送、排名操纵或加密货币挖矿。",
                "不执行旨在对用户设备或网络造成意外负载或损害的处理。"
              ]
            },
            {
              "h3": "7-4. Google Play 目标 API 级别政策"
            },
            {
              "ul": [
                "本应用在发布时构建以满足 Google Play 要求的目标 API 级别要求。",
                "我们将根据 Google 要求的变化适当更新目标 API 级别并修改应用。"
              ]
            },
            {
              "h3": "7-5. 禁止欺骗行为"
            },
            {
              "ul": [
                "本应用注意避免欺骗用户的 UI 设计或诱导误触的显示（所谓的令人困惑的按钮布局等）。",
                "本应用不是为了在后台执行用户不知道目的的通信或处理而设计的。",
                "如果将来引入广告，我们将优先考虑 Google Play 政策和用户友好性。"
              ]
            }
          ]
        },
        {
          "title": "8. 有偿道具（应用内购买）使用条款",
          "blocks": [
            {
              "p": "本条款规定了有偿道具（应用内购买）的使用条件。请通过以下链接查看完整条款。"
            },
            {
              "link": {
                "href": "/zh/item_terms_of_use/",
                "label": "在小窗口中查看有偿道具使用条款"
              }
            }
          ]
        },
        {
          "title": "9. 安全措施",
          "blocks": [
            {
              "ul": [
                "虽然本应用设计为不收集用户数据，但如果将来添加处理数据的功能，我们将努力实施适当的技术和组织安全措施，以防止未经授权的访问、篡改和泄露。",
                "此外，我们将定期审查 Play 家庭政策和相关政策，并根据需要修改应用和运营。"
              ]
            }
          ]
        },
        {
          "title": "10. 关于本隐私政策的变更",
          "blocks": [
            {
              "p": "本隐私政策的内容可能会根据需要进行更改。"
            },
            {
              "ul": [
                "如果有重大变更，我们将在本应用或 App Flux Portal 上公告。",
                "修订后的隐私政策将从发布到本网站时起生效。"
              ]
            }
          ]
        }
      ]
    },
    "terms": {
      "title": "有偿道具（应用内购买）使用条款",
      "intro": "本条款（以下简称“本条款”）规定了本应用内提供的有偿道具（以下简称“本道具”）的使用条件。用户使用本应用即视为同意本条款。",
      "articles": [
        {
          "title": "第1条（关于有偿道具）",
          "body": "本应用内提供的有偿道具为一次性购买的数字内容。购买后，用户获得在本应用内使用该道具的权利。有偿道具不保证永久运行或未来持续可用。"
        },
        {
          "title": "第2条（使用环境）",
          "body": "本道具基于购买时的应用及运行环境提供。因系统更新、设备更换、制造商或运营商规格变更等原因，可能导致本道具无法正常使用。对此开发者不承担任何责任。"
        },
        {
          "title": "第3条（更新与持续提供）",
          "body": "开发者不负有持续更新或功能改进本应用及本道具的义务。开发者可在不另行通知的情况下变更、暂停或终止本应用或本道具的提供。"
        },
        {
          "title": "第4条（服务终止）",
          "body": "因运营或技术原因，开发者可能终止本应用或本道具的提供。服务终止后，可能无法继续使用本道具。"
        },
        {
          "title": "第5条（退款）",
          "body": "由于数字内容的性质，购买后原则上不予退款。但以 Google Play 等平台规定的退款政策为准。"
        },
        {
          "title": "第6条（免责声明）",
          "body": "开发者对用户因使用本应用或本道具而产生的任何损失不承担责任。本应用及本道具按“现状”提供。"
        },
        {
          "title": "第7条（条款变更）",
          "body": "开发者可根据需要变更本条款。变更后的条款在本应用或相关网站发布时生效。"
        },
        {
          "title": "第8条（适用法律）",
          "body": "本条款适用并按日本法律解释。"
        }
      ]
    }
  }
}
